INSERT INTO users(first_name, last_name, email, about_me, picture_url) VALUES
('Elene', 'Enukidze', 'elene@gmail.com', 'CS student at freeuni', NULL),
('Giorgi', 'Giorgidze', 'giorgi125giorgi@gmail.com', 'math tutor', NULL),
('Ana', 'anashvili', 'anaanashvili7@gmail.com', 'Certified Tbilisi tour guide', NULL),
('Tim', 'Tom', 'TimaTom555@gmail.com', '...', NULL),
('Lizi', 'Nanava', 'Lizi@gmail.com', 'CS student', NULL),
('Davit', 'Palelashvili', 'davit@gmail.com', 'Coding', NULL),
('Ato', 'Babilodze', 'ato@gmail.com', 'savardzelimdivani', NULL),
('Saba', 'Makhniashvili', 'saba@gmail.com', 'Codeforces', NULL);



INSERT INTO services (provider_id, title, bio, picture_url, category, price) VALUES
                                                                                 (1, 'Pottery Basics', 'Hands-on pottery workshop', NULL, 'Arts', 200.00),
                                                                                 (2, 'Calculus Tutoring', 'Advanced math help', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Tbilisi City Tour', 'Customized local tours', NULL, 'Travel', 200.00),
                                                                                 (4, 'Programming Basics', 'Intro to coding', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Painting Class', 'Learn to paint landscapes', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Python Workshop', 'Backend development', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Language Lessons', 'Learn Georgian quickly', NULL, 'Education', 200.00),
                                                                                 (8, 'Data Structures', 'Competitive programming prep', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Ceramics Design', 'Advanced pottery techniques', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Linear Algebra', 'University level math', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Gastronomic Tour', 'Explore Georgian food', NULL, 'Travel', 200.00),
                                                                                 (4, 'Web Development', 'Full stack basics', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Sketching 101', 'Foundations of drawing', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Database Design', 'SQL and NoSQL', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'History of Tbilisi', 'A deep dive into history', NULL, 'Education', 200.00),
                                                                                 (8, 'Algorithm Design', 'Optimization techniques', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Glazing Techniques', 'Final touches in pottery', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Differential Equations', 'Solving complex problems', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Mountain Hiking', 'Day trip in the Caucasus', NULL, 'Travel', 200.00),
                                                                                 (4, 'JavaScript ES6', 'Modern web scripting', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Watercolor Painting', 'Beginner watercolor skills', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Cloud Infrastructure', 'Introduction to AWS', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Literary Analysis', 'Reading classic literature', NULL, 'Education', 200.00),
                                                                                 (8, 'Game Architecture', 'Advanced unity topics', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Kiln Operation', 'Understanding firing', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Probability Theory', 'Fundamentals of chance', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Wine Tasting Tour', 'Local winery visit', NULL, 'Travel', 200.00),
                                                                                 (4, 'React Framework', 'Building interfaces', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Digital Illustration', 'Tablets and software', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Security Basics', 'Web vulnerability audit', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Public Speaking', 'Build your confidence', NULL, 'Education', 200.00),
                                                                                 (8, 'Machine Learning', 'Intro to neural networks', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Sculpting Fundamentals', 'Modeling clay shapes', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Discrete Mathematics', 'Logic for computer science', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'City Photography', 'Best spots in Tbilisi', NULL, 'Travel', 200.00),
                                                                                 (4, 'Node.js Basics', 'Server-side javascript', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Charcoal Drawing', 'Light and shadow', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Git Workshop', 'Version control mastery', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Business English', 'Professional writing', NULL, 'Education', 200.00),
                                                                                 (8, 'System Design', 'Scalable architecture', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Advanced Wheel Throwing', 'Challenging shapes', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Statistics 101', 'Data analysis basics', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Art Gallery Tour', 'Visit local exhibitions', NULL, 'Travel', 200.00),
                                                                                 (4, 'CSS Layouts', 'Flexbox and Grid', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Oil Painting', 'Canvas techniques', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'REST API Design', 'Standardized endpoints', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Creative Writing', 'Developing stories', NULL, 'Education', 200.00),
                                                                                 (8, 'Data Science Intro', 'Pandas and NumPy', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Pottery Decoration', 'Painting on ceramics', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Number Theory', 'Fascinating patterns', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Hidden Tbilisi', 'Secret courtyard tour', NULL, 'Travel', 200.00),
                                                                                 (4, 'TypeScript Basics', 'Strongly typed code', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Printmaking Workshop', 'Creating patterns', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Docker Essentials', 'Containerizing apps', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Financial Literacy', 'Personal finance guide', NULL, 'Education', 200.00),
                                                                                 (8, 'Backend Scaling', 'Distributed systems', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Hand-building Clay', 'Coil and slab methods', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Geometry Review', 'Shapes and measurements', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Old Town Architecture', 'Historical tour', NULL, 'Travel', 200.00),
                                                                                 (4, 'Responsive Design', 'Mobile-first approach', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Portrait Drawing', 'Face structure', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Linux Commands', 'Terminal proficiency', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Time Management', 'Boost your productivity', NULL, 'Education', 200.00),
                                                                                 (8, 'Python Data Scraping', 'Gathering web data', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Clay Preparation', 'Processing raw material', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Trigonometry', 'Angles and waves', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Night Tour', 'Tbilisi at night', NULL, 'Travel', 200.00),
                                                                                 (4, 'Bootstrap Framework', 'Speedy UI design', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Acrylic Painting', 'Modern techniques', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'API Testing', 'Postman for developers', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Debate Skills', 'Critical thinking', NULL, 'Education', 200.00),
                                                                                 (8, 'Unit Testing', 'Writing reliable code', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Pottery Glazing', 'Colors and textures', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Math Logic', 'Formal proofs', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Village Day Trip', 'Near city getaway', NULL, 'Travel', 200.00),
                                                                                 (4, 'SASS/SCSS', 'Efficient stylesheets', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Colored Pencils', 'Drawing textures', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Shell Scripting', 'Bash automation', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Effective Study', 'Learning techniques', NULL, 'Education', 200.00),
                                                                                 (8, 'Game Physics', 'Intro to mechanics', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Pottery Molds', 'Creating copies', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Advanced Algebra', 'Polynomails and roots', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Local Markets Tour', 'Explore food hubs', NULL, 'Travel', 200.00),
                                                                                 (4, 'Tailwind CSS', 'Utility-first styling', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Perspective Drawing', '3D on 2D space', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'SQL Optimization', 'Fast database queries', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Project Management', 'Planning foundations', NULL, 'Education', 200.00),
                                                                                 (8, 'Data Visualization', 'D3.js or Chart.js', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Slip Casting', 'Advanced techniques', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Vector Calculus', 'Spatial analysis', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Museum Tour', 'Tbilisi museums', NULL, 'Travel', 200.00),
                                                                                 (4, 'Web Accessibility', 'Inclusive design', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Life Drawing', 'Human figure studies', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Nginx Setup', 'Server configuration', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Networking Basics', 'Build connections', NULL, 'Education', 200.00),
                                                                                 (8, 'Refactoring Code', 'Clean code practices', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Kiln Maintenance', 'Repairing pottery tools', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Topology Intro', 'Shape analysis', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Street Art Tour', 'Tbilisi graffiti', NULL, 'Travel', 200.00),
                                                                                 (4, 'Animations CSS', 'Web movement', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Ink Drawing', 'Classic illustration', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Database Backup', 'Recovery strategies', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Decision Making', 'Analytical choices', NULL, 'Education', 200.00),
                                                                                 (8, 'Open Source', 'Contributing to projects', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Clay Mixing', 'Recipes for clay', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Complex Numbers', 'Imaginary plane', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Architecture Tour', 'Old vs New Tbilisi', NULL, 'Travel', 200.00),
                                                                                 (4, 'Form Validation', 'User input safety', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Anatomy Drawing', 'Muscles and bone', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Redis Caching', 'Improve performance', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Conflict Resolution', 'Mediation skills', NULL, 'Education', 200.00),
                                                                                 (8, 'Async Programming', 'Handling events', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Pottery Studio Safety', 'Essential practices', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Game Math', 'Coordinate systems', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Walking Tour', 'City center highlights', NULL, 'Travel', 200.00),
                                                                                 (4, 'Web Forms', 'HTML structure', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Color Theory', 'Mixing palettes', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'API Authentication', 'JWT and OAuth', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Mindfulness', 'Stress reduction', NULL, 'Education', 200.00),
                                                                                 (8, 'Performance Tuning', 'Code optimization', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Finishing Techniques', 'Smoothing and sanding', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Graph Theory', 'Connecting networks', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Religious Sites Tour', 'Churches of Tbilisi', NULL, 'Travel', 200.00),
                                                                                 (4, 'JSON Handling', 'Data serialization', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Pastels Workshop', 'Blending techniques', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Search Indexing', 'Elasticsearch intro', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Goal Setting', 'SMART goals', NULL, 'Education', 200.00),
                                                                                 (8, 'Memory Management', 'Efficient heap usage', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Pottery History', 'Cultural significance', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Abstract Algebra', 'Structures in math', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Botanical Garden Tour', 'Nature inside city', NULL, 'Travel', 200.00),
                                                                                 (4, 'DOM Manipulation', 'Scripting elements', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Gouache Painting', 'Opaque watercolors', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Load Balancing', 'Scalable servers', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Critical Reading', 'Analytical skills', NULL, 'Education', 200.00),
                                                                                 (8, 'Parallel Computing', 'Threading basics', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Functional Pottery', 'Making cups and bowls', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Calculus Basics', 'Derivatives intro', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Film Set Tour', 'Tbilisi film spots', NULL, 'Travel', 200.00),
                                                                                 (4, 'Browser Developer Tools', 'Debugging skills', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Drawing Shading', 'Pencil control', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Web Sockets', 'Real-time messaging', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Memory Techniques', 'Better retention', NULL, 'Education', 200.00),
                                                                                 (8, 'Concurrency', 'Handling tasks', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Creative Pottery', 'Express yourself', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Linear Systems', 'Matrix operations', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Cycling Tour', 'See city on bike', NULL, 'Travel', 200.00),
                                                                                 (4, 'Fetch API', 'HTTP requests', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Markers Drawing', 'Solid colors', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Server Logs', 'Analysis and alerts', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Interview Prep', 'Soft skills', NULL, 'Education', 200.00),
                                                                                 (8, 'Debugging Tips', 'Solving hard bugs', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Clay Modeling', 'Character building', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Geometry proofs', 'Logic steps', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Tea Tasting', 'Cultural tradition', NULL, 'Travel', 200.00),
                                                                                 (4, 'ES6 Modules', 'Importing scripts', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Still Life', 'Drawing from life', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Nginx Reverse Proxy', 'Gateway setup', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Active Listening', 'Better communication', NULL, 'Education', 200.00),
                                                                                 (8, 'Software Patterns', 'Design choices', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Pottery Textures', 'Carving patterns', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Series and Sequences', 'Math growth', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Bakery Tour', 'Fresh bread spots', NULL, 'Travel', 200.00),
                                                                                 (4, 'Local Storage', 'Browser data', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Urban Sketching', 'Drawing on streets', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'SSH Access', 'Remote server control', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Writing Essays', 'Structure and style', NULL, 'Education', 200.00),
                                                                                 (8, 'Code Review', 'Team standards', NULL, 'IT & Programming', 200.00),
                                                                                 (1, 'Glaze Mixing', 'Chemistry of colors', NULL, 'Music & Arts', 200.00),
                                                                                 (2, 'Integral Calculus', 'Calculating area', NULL, 'Math & Physics', 200.00),
                                                                                 (3, 'Street Food Tour', 'Local eats', NULL, 'Travel', 200.00),
                                                                                 (4, 'Canvas API', 'Drawing in browser', NULL, 'IT & Programming', 200.00),
                                                                                 (5, 'Illustration Basics', 'Storytelling', NULL, 'Music & Arts', 200.00),
                                                                                 (6, 'Database Migrations', 'Versioning data', NULL, 'IT & Programming', 200.00),
                                                                                 (7, 'Negotiation', 'Finding balance', NULL, 'Education', 200.00),
                                                                                 (8, 'Clean Architecture', 'Modular software', NULL, 'IT & Programming', 200.00);

INSERT INTO bookings(taker_id, service_id) VALUES
(1, 3),
(4, 1),
(3, 1),
(4, 4),
(6, 4),
(7, 4),
(7, 1);