-- INSERT INTO users (first_name, last_name, email, password_hash, about_me, image_path, is_enabled, verification_code) VALUES
--          ('Amara', 'Okonkwo', 'amara.o@example.com', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Architectural designer based in Lagos. I draw inspiration from the vibrant textures of Nigerian street life and sustainable urban planning. When I am not drafting blueprints, I am likely exploring local art galleries or teaching workshops on bamboo construction techniques to architecture students.', NULL, 1, NULL),
--          ('Hiroshi', 'Tanaka', 'h.tanaka@example.jp', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Systems engineer from Kyoto with a passion for vintage mechanical watches and modular synthesis. I spend my weekends restoring antique clocks and experimenting with ambient soundscapes in my home studio.', NULL, 1, NULL),
--          ('Elena', 'Petrova', 'elena.pet@example.bg', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Botanist and documentary photographer. I spend most of my year trekking through the Balkan mountains documenting rare alpine flora. I am deeply concerned with climate change and often speak at universities about preservation efforts. Looking for interesting travel companions for my next expedition.', NULL, 1, NULL),
--          ('Mateo', 'Fernández', 'mateo.f@example.ar', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Professional barista in Buenos Aires. I take coffee science very seriously—everything from bean origin to water mineral content. When the cafe closes, I play jazz bass in a local ensemble.', NULL, 1, NULL),
--          ('Sanaa', 'Al-Mansour', 'sanaa.am@example.ae', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Digital marketing strategist with a focus on tech startups. I moved to Dubai three years ago and love the fast-paced energy. I enjoy marathon training and finding the best hidden food spots in the city.', NULL, 1, NULL),
--          ('Lars', 'Jensen', 'lars.j@example.dk', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Furniture designer from Copenhagen. Minimalism is my philosophy, but I believe every object should tell a story. I spend my winters cross-country skiing and my summers restoring a wooden sailboat.', NULL, 1, NULL),
--          ('Fatoumata', 'Diop', 'f.diop@example.sn', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Human rights lawyer working in Dakar. My life is balanced between intense courtroom debates and quiet evenings practicing traditional Senegalese weaving.', NULL, 1, NULL),
--          ('Alessandro', 'Rossi', 'ale.rossi@example.it', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Culinary arts student in Florence. I am currently obsessing over the perfect sourdough fermentation process. On Sundays, I volunteer at a local community kitchen.', NULL, 1, NULL),
--          ('Mei', 'Lin', 'mei.lin.dev@example.cn', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Full-stack developer. I love solving complex algorithmic puzzles and contributing to open-source climate data projects. I am a huge fan of retro science fiction and black coffee.', NULL, 1, NULL),
--          ('Kofi', 'Mensah', 'kofi.m@example.gh', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Journalist covering environmental issues across West Africa. I believe stories have the power to change policies. I am an amateur ornithologist and spend my mornings birdwatching in the wetlands.', NULL, 1, NULL),
--          ('Ingrid', 'Berg', 'ingrid.b@example.no', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Environmental geologist specializing in glacier movement. I have lived in remote field stations for months at a time, but I always come back for good books and strong dark chocolate.', NULL, 1, NULL),
--          ('Arjun', 'Patel', 'arjun.p@example.in', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Astrophysics PhD student. When I am not mapping stars, I am teaching myself how to play the tabla. I love collaborative science projects and late-night philosophical discussions.', NULL, 1, NULL),
--          ('Zeynep', 'Yilmaz', 'zeynep.y@example.tr', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Graphic designer based in Istanbul. I work with traditional Anatolian patterns merged with modern UI/UX design. Passionate about sustainable fashion and local handicraft preservation.', NULL, 1, NULL),
--          ('Javier', 'Silva', 'javier.s@example.cl', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Astronomer and avid climber. I split my time between the observatories in the Atacama Desert and scaling the peaks of the Andes. Nothing beats the view of the Milky Way from a mountain bivouac.', NULL, 1, NULL),
--          ('Chloe', 'Dubois', 'chloe.d@example.fr', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Restoration expert for historical paintings in Paris. I enjoy the painstaking process of uncovering centuries-old layers of paint. I spend my spare time cycling through the French countryside.', NULL, 1, NULL),
--          ('Viktor', 'Novak', 'vik.novak@example.cz', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Independent filmmaker and photographer. I focus on urban decay and social change. I am usually carrying three different cameras and a notebook for screenplays.', NULL, 1, NULL),
--          ('Yuki', 'Sato', 'yuki.sato@example.jp', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Library science researcher. My life is essentially an archive of rare manuscripts and lost stories. I am currently learning Latin and enjoy quiet afternoons in historical archives.', NULL, 1, NULL),
--          ('Sofia', 'Müller', 'sofia.m@example.de', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Data analyst by day, professional urban gardener by night. I am obsessed with vertical farming and making Berlin a greener city, one balcony at a time. I love dogs and sci-fi podcasts.', NULL, 1, NULL),
--          ('Hamza', 'Ibrahim', 'hamza.i@example.eg', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'History teacher and amateur archaeologist. I spend my weekends near the Nile trying to map unrecorded burial sites. I am passionate about keeping history alive for the younger generation.', NULL, 1, NULL),                                                                                                                   ('Lucia', 'Gomes', 'lucia.g@example.br', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Marine biologist focused on reef conservation in Brazil. My work involves diving, data collection, and fighting for ocean protection. When on land, I enjoy capoeira and healthy cooking.', NULL, 1, NULL);
--
-- INSERT INTO services (provider_id, title, bio, image_path, category, price) VALUES
--          (1, 'Introduction to Sustainable Architecture', 'In this comprehensive workshop, we explore the integration of eco-friendly materials into modern home design. We will look at natural ventilation strategies, solar orientation, and the use of reclaimed materials to reduce your carbon footprint while maintaining aesthetic beauty.', NULL, 'arch', 75.00),
--          (1, 'Lagos Urban Planning Tour', 'Join me for an immersive walking tour of Lagos, where we analyze the intersection of traditional architecture and rapid urbanization. We will visit key sites that showcase how sustainable design is slowly transforming the city landscape.', NULL, 'touring',40.00),
--
--          (2, 'Mastering C# for Unity Development', 'From absolute beginner to building your first 2D platformer. This course covers core C# syntax, object-oriented programming principles, and how they apply specifically to the Unity game engine. Perfect for those looking to start their career in game dev.', NULL, 'game development',120.00),
--          (2, 'Vintage Watch Restoration Basics', 'A delicate, meditative dive into the world of horology. Learn how to safely open, clean, and re-oil antique mechanical movements. I provide the tools and guidance; you bring the patience.', NULL, 'watch restoration',90.00),
--
--          (3, 'Alpine Flora Identification Field Trip', 'Spend a day with me in the mountains learning how to identify endemic plant species. We will discuss the ecosystem, the challenges of high-altitude life, and how climate change is affecting these fragile habitats.', NULL,'trip', 60.00),
--          (3, 'Nature Photography Masterclass', 'Capture the wilderness like a pro. This course covers composition, lighting in diverse environments, and how to tell a story through botanical photography. Bring your camera and sturdy hiking boots.', NULL, 'photography',55.00),
--
--          (4, 'The Science of Espresso Extraction', 'Beyond the button press. Learn about grind size, water pressure, puck preparation, and the chemistry behind the perfect shot. We will dial in a coffee together until it tastes balanced and sweet.', NULL, 'coffe making classes',45.00),
--          (4, 'Jazz Bass Fundamentals', 'A beginner-friendly guide to walking bass lines and jazz improvisation. We will cover standard chord progressions, rhythm, and how to find your groove within an ensemble.', NULL, 'learn jazz culture',35.00),
--
--          (5, 'Tech Startup Branding Strategy', 'How to define your voice in a crowded market. We will go over audience segmentation, content strategy, and how to build a brand identity that resonates with early adopters in the tech space.', NULL, 'startup branding',150.00),
--          (5, 'Professional Social Media Audit', 'Struggling to gain traction? I will provide a deep dive into your current digital presence, offering actionable insights on how to improve your engagement and conversion rates.', NULL, 'social media',85.00),
--
--          (6, 'Danish Modern Furniture Workshop', 'Learn to build a simple, elegant side table using traditional joinery techniques. We emphasize functionality, clean lines, and high-quality craftsmanship.', NULL, 'furniture',200.00),
--          (6, 'Introduction to Nordic Woodworking', 'Learn the basics of hand-tool woodworking. We will cover timber selection, sharpening your chisels, and the basics of creating durable, beautiful joints that last a lifetime.', NULL,'woodworking', 110.00),
--
--          (7, 'Introduction to Civil Rights Advocacy', 'A foundational course on understanding your rights and how to navigate legal systems. We will look at case studies from around the world and discuss how to engage in ethical advocacy.', NULL, 'civil rights',65.00),
--          (7, 'Traditional Weaving Workshop', 'A workshop on Senegalese weaving techniques. This is a chance to learn a beautiful, ancient craft while we discuss the history and cultural significance of textile arts in West Africa.', NULL, 'weaving',50.00),
--
--          (8, 'Authentic Sourdough Baking', 'Forget store-bought loaves. Learn how to create, feed, and maintain your own sourdough starter, and master the art of the perfect, crusty artisan loaf.', NULL, 'cooking',40.00),
--         (8, 'Italian Home Cooking Secrets', 'Simple, high-quality ingredients made right. We will focus on the fundamentals of handmade pasta, perfect marinara, and classic desserts that impress every time.', NULL, 'cooking', 55.00),
--          (1, 'Pottery Basics', 'Hands-on pottery workshop', NULL, 'Arts', 200.00),
--          (2, 'Calculus Tutoring', 'Advanced math help', NULL, 'Math & Physics', 200.00),
--          (3, 'Tbilisi City Tour', 'Customized local tours', NULL, 'Travel', 200.00),
--          (4, 'Programming Basics', 'Intro to coding', NULL, 'IT & Programming', 200.00),
--          (5, 'Painting Class', 'Learn to paint landscapes', NULL, 'Music & Arts', 200.00),
--          (6, 'Python Workshop', 'Backend development', NULL, 'IT & Programming', 200.00),
--          (7, 'Language Lessons', 'Learn Georgian quickly', NULL, 'Education', 200.00),
--          (8, 'Data Structures', 'Competitive programming prep', NULL, 'IT & Programming', 200.00),
--          (1, 'Ceramics Design', 'Advanced pottery techniques', NULL, 'Music & Arts', 200.00),
--          (2, 'Linear Algebra', 'University level math', NULL, 'Math & Physics', 200.00),
--          (3, 'Gastronomic Tour', 'Explore Georgian food', NULL, 'Travel', 200.00),
--          (4, 'Web Development', 'Full stack basics', NULL, 'IT & Programming', 200.00),
--          (5, 'Sketching 101', 'Foundations of drawing', NULL, 'Music & Arts', 200.00),
--          (6, 'Database Design', 'SQL and NoSQL', NULL, 'IT & Programming', 200.00),
--          (7, 'History of Tbilisi', 'A deep dive into history', NULL, 'Education', 200.00),
--          (8, 'Algorithm Design', 'Optimization techniques', NULL, 'IT & Programming', 200.00),
--          (1, 'Glazing Techniques', 'Final touches in pottery', NULL, 'Music & Arts', 200.00),
--          (2, 'Differential Equations', 'Solving complex problems', NULL, 'Math & Physics', 200.00),
--          (3, 'Mountain Hiking', 'Day trip in the Caucasus', NULL, 'Travel', 200.00),
--          (4, 'JavaScript ES6', 'Modern web scripting', NULL, 'IT & Programming', 200.00),
--          (5, 'Watercolor Painting', 'Beginner watercolor skills', NULL, 'Music & Arts', 200.00),
--          (6, 'Cloud Infrastructure', 'Introduction to AWS', NULL, 'IT & Programming', 200.00),
--          (7, 'Literary Analysis', 'Reading classic literature', NULL, 'Education', 200.00),
--          (8, 'Game Architecture', 'Advanced unity topics', NULL, 'IT & Programming', 200.00),
--          (1, 'Kiln Operation', 'Understanding firing', NULL, 'Music & Arts', 200.00),
--          (2, 'Probability Theory', 'Fundamentals of chance', NULL, 'Math & Physics', 200.00),
--          (3, 'Wine Tasting Tour', 'Local winery visit', NULL, 'Travel', 200.00),
--          (4, 'React Framework', 'Building interfaces', NULL, 'IT & Programming', 200.00),
--          (5, 'Digital Illustration', 'Tablets and software', NULL, 'Music & Arts', 200.00),
--          (6, 'Security Basics', 'Web vulnerability audit', NULL, 'IT & Programming', 200.00),
--          (7, 'Public Speaking', 'Build your confidence', NULL, 'Education', 200.00),
--          (8, 'Machine Learning', 'Intro to neural networks', NULL, 'IT & Programming', 200.00),
--          (1, 'Sculpting Fundamentals', 'Modeling clay shapes', NULL, 'Music & Arts', 200.00),
--          (2, 'Discrete Mathematics', 'Logic for computer science', NULL, 'Math & Physics', 200.00),
--          (3, 'City Photography', 'Best spots in Tbilisi', NULL, 'Travel', 200.00),
--          (4, 'Node.js Basics', 'Server-side javascript', NULL, 'IT & Programming', 200.00),
--          (5, 'Charcoal Drawing', 'Light and shadow', NULL, 'Music & Arts', 200.00),
--          (6, 'Git Workshop', 'Version control mastery', NULL, 'IT & Programming', 200.00),
--          (7, 'Business English', 'Professional writing', NULL, 'Education', 200.00),
--          (8, 'System Design', 'Scalable architecture', NULL, 'IT & Programming', 200.00),
--          (1, 'Advanced Wheel Throwing', 'Challenging shapes', NULL, 'Music & Arts', 200.00),
--          (2, 'Statistics 101', 'Data analysis basics', NULL, 'Math & Physics', 200.00),
--          (3, 'Art Gallery Tour', 'Visit local exhibitions', NULL, 'Travel', 200.00),
--          (4, 'CSS Layouts', 'Flexbox and Grid', NULL, 'IT & Programming', 200.00),
--          (5, 'Oil Painting', 'Canvas techniques', NULL, 'Music & Arts', 200.00),
--          (6, 'REST API Design', 'Standardized endpoints', NULL, 'IT & Programming', 200.00),
--          (7, 'Creative Writing', 'Developing stories', NULL, 'Education', 200.00),
--          (8, 'Data Science Intro', 'Pandas and NumPy', NULL, 'IT & Programming', 200.00),
--          (1, 'Pottery Decoration', 'Painting on ceramics', NULL, 'Music & Arts', 200.00),
--          (2, 'Number Theory', 'Fascinating patterns', NULL, 'Math & Physics', 200.00),
--          (3, 'Hidden Tbilisi', 'Secret courtyard tour', NULL, 'Travel', 200.00),
--          (4, 'TypeScript Basics', 'Strongly typed code', NULL, 'IT & Programming', 200.00),
--          (5, 'Printmaking Workshop', 'Creating patterns', NULL, 'Music & Arts', 200.00),
--          (6, 'Docker Essentials', 'Containerizing apps', NULL, 'IT & Programming', 200.00),
--          (7, 'Financial Literacy', 'Personal finance guide', NULL, 'Education', 200.00),
--          (8, 'Backend Scaling', 'Distributed systems', NULL, 'IT & Programming', 200.00),
--          (1, 'Hand-building Clay', 'Coil and slab methods', NULL, 'Music & Arts', 200.00),
--          (2, 'Geometry Review', 'Shapes and measurements', NULL, 'Math & Physics', 200.00),
--          (3, 'Old Town Architecture', 'Historical tour', NULL, 'Travel', 200.00),
--          (4, 'Responsive Design', 'Mobile-first approach', NULL, 'IT & Programming', 200.00),
--          (5, 'Portrait Drawing', 'Face structure', NULL, 'Music & Arts', 200.00),
--          (6, 'Linux Commands', 'Terminal proficiency', NULL, 'IT & Programming', 200.00),
--          (7, 'Time Management', 'Boost your productivity', NULL, 'Education', 200.00),
--          (8, 'Python Data Scraping', 'Gathering web data', NULL, 'IT & Programming', 200.00),
--          (1, 'Clay Preparation', 'Processing raw material', NULL, 'Music & Arts', 200.00),
--          (2, 'Trigonometry', 'Angles and waves', NULL, 'Math & Physics', 200.00),
--          (3, 'Night Tour', 'Tbilisi at night', NULL, 'Travel', 200.00),
--          (4, 'Bootstrap Framework', 'Speedy UI design', NULL, 'IT & Programming', 200.00),
--          (5, 'Acrylic Painting', 'Modern techniques', NULL, 'Music & Arts', 200.00),
--          (6, 'API Testing', 'Postman for developers', NULL, 'IT & Programming', 200.00),
--          (7, 'Debate Skills', 'Critical thinking', NULL, 'Education', 200.00),
--          (8, 'Unit Testing', 'Writing reliable code', NULL, 'IT & Programming', 200.00),
--          (1, 'Pottery Glazing', 'Colors and textures', NULL, 'Music & Arts', 200.00),
--          (2, 'Math Logic', 'Formal proofs', NULL, 'Math & Physics', 200.00),
--          (3, 'Village Day Trip', 'Near city getaway', NULL, 'Travel', 200.00),
--          (4, 'SASS/SCSS', 'Efficient stylesheets', NULL, 'IT & Programming', 200.00),
--          (5, 'Colored Pencils', 'Drawing textures', NULL, 'Music & Arts', 200.00),
--          (6, 'Shell Scripting', 'Bash automation', NULL, 'IT & Programming', 200.00),
--          (7, 'Effective Study', 'Learning techniques', NULL, 'Education', 200.00),
--          (8, 'Game Physics', 'Intro to mechanics', NULL, 'IT & Programming', 200.00),
--          (1, 'Pottery Molds', 'Creating copies', NULL, 'Music & Arts', 200.00),
--          (2, 'Advanced Algebra', 'Polynomails and roots', NULL, 'Math & Physics', 200.00),
--          (3, 'Local Markets Tour', 'Explore food hubs', NULL, 'Travel', 200.00),
--          (4, 'Tailwind CSS', 'Utility-first styling', NULL, 'IT & Programming', 200.00),
--          (5, 'Perspective Drawing', '3D on 2D space', NULL, 'Music & Arts', 200.00),
--          (6, 'SQL Optimization', 'Fast database queries', NULL, 'IT & Programming', 200.00),
--          (7, 'Project Management', 'Planning foundations', NULL, 'Education', 200.00),
--          (8, 'Data Visualization', 'D3.js or Chart.js', NULL, 'IT & Programming', 200.00),
--          (1, 'Slip Casting', 'Advanced techniques', NULL, 'Music & Arts', 200.00),
--          (2, 'Vector Calculus', 'Spatial analysis', NULL, 'Math & Physics', 200.00),
--          (3, 'Museum Tour', 'Tbilisi museums', NULL, 'Travel', 200.00),
--          (4, 'Web Accessibility', 'Inclusive design', NULL, 'IT & Programming', 200.00),
--          (5, 'Life Drawing', 'Human figure studies', NULL, 'Music & Arts', 200.00),
--          (6, 'Nginx Setup', 'Server configuration', NULL, 'IT & Programming', 200.00),
--          (7, 'Networking Basics', 'Build connections', NULL, 'Education', 200.00),
--          (8, 'Refactoring Code', 'Clean code practices', NULL, 'IT & Programming', 200.00),
--          (1, 'Kiln Maintenance', 'Repairing pottery tools', NULL, 'Music & Arts', 200.00),
--          (2, 'Topology Intro', 'Shape analysis', NULL, 'Math & Physics', 200.00),
--          (3, 'Street Art Tour', 'Tbilisi graffiti', NULL, 'Travel', 200.00),
--          (4, 'Animations CSS', 'Web movement', NULL, 'IT & Programming', 200.00),
--          (5, 'Ink Drawing', 'Classic illustration', NULL, 'Music & Arts', 200.00),
--          (6, 'Database Backup', 'Recovery strategies', NULL, 'IT & Programming', 200.00),
--          (7, 'Decision Making', 'Analytical choices', NULL, 'Education', 200.00),
--          (8, 'Open Source', 'Contributing to projects', NULL, 'IT & Programming', 200.00),
--          (1, 'Clay Mixing', 'Recipes for clay', NULL, 'Music & Arts', 200.00),
--          (2, 'Complex Numbers', 'Imaginary plane', NULL, 'Math & Physics', 200.00),
--          (3, 'Architecture Tour', 'Old vs New Tbilisi', NULL, 'Travel', 200.00),
--          (4, 'Form Validation', 'User input safety', NULL, 'IT & Programming', 200.00),
--          (5, 'Anatomy Drawing', 'Muscles and bone', NULL, 'Music & Arts', 200.00),
--          (6, 'Redis Caching', 'Improve performance', NULL, 'IT & Programming', 200.00),
--          (7, 'Conflict Resolution', 'Mediation skills', NULL, 'Education', 200.00),
--          (8, 'Async Programming', 'Handling events', NULL, 'IT & Programming', 200.00),
--          (1, 'Pottery Studio Safety', 'Essential practices', NULL, 'Music & Arts', 200.00),
--          (2, 'Game Math', 'Coordinate systems', NULL, 'Math & Physics', 200.00),
--          (3, 'Walking Tour', 'City center highlights', NULL, 'Travel', 200.00),
--          (4, 'Web Forms', 'HTML structure', NULL, 'IT & Programming', 200.00),
--          (5, 'Color Theory', 'Mixing palettes', NULL, 'Music & Arts', 200.00),
--          (6, 'API Authentication', 'JWT and OAuth', NULL, 'IT & Programming', 200.00),
--          (7, 'Mindfulness', 'Stress reduction', NULL, 'Education', 200.00),
--          (8, 'Performance Tuning', 'Code optimization', NULL, 'IT & Programming', 200.00),
--          (1, 'Finishing Techniques', 'Smoothing and sanding', NULL, 'Music & Arts', 200.00),
--          (2, 'Graph Theory', 'Connecting networks', NULL, 'Math & Physics', 200.00),
--          (3, 'Religious Sites Tour', 'Churches of Tbilisi', NULL, 'Travel', 200.00),
--          (4, 'JSON Handling', 'Data serialization', NULL, 'IT & Programming', 200.00),
--          (5, 'Pastels Workshop', 'Blending techniques', NULL, 'Music & Arts', 200.00),
--          (6, 'Search Indexing', 'Elasticsearch intro', NULL, 'IT & Programming', 200.00),
--          (7, 'Goal Setting', 'SMART goals', NULL, 'Education', 200.00),
--          (8, 'Memory Management', 'Efficient heap usage', NULL, 'IT & Programming', 200.00),
--          (1, 'Pottery History', 'Cultural significance', NULL, 'Music & Arts', 200.00),
--          (2, 'Abstract Algebra', 'Structures in math', NULL, 'Math & Physics', 200.00),
--          (3, 'Botanical Garden Tour', 'Nature inside city', NULL, 'Travel', 200.00),
--          (4, 'DOM Manipulation', 'Scripting elements', NULL, 'IT & Programming', 200.00),
--          (5, 'Gouache Painting', 'Opaque watercolors', NULL, 'Music & Arts', 200.00),
--          (6, 'Load Balancing', 'Scalable servers', NULL, 'IT & Programming', 200.00),
--          (7, 'Critical Reading', 'Analytical skills', NULL, 'Education', 200.00),
--          (8, 'Parallel Computing', 'Threading basics', NULL, 'IT & Programming', 200.00),
--          (1, 'Functional Pottery', 'Making cups and bowls', NULL, 'Music & Arts', 200.00),
--          (2, 'Calculus Basics', 'Derivatives intro', NULL, 'Math & Physics', 200.00),
--          (3, 'Film Set Tour', 'Tbilisi film spots', NULL, 'Travel', 200.00),
--          (4, 'Browser Developer Tools', 'Debugging skills', NULL, 'IT & Programming', 200.00),
--          (5, 'Drawing Shading', 'Pencil control', NULL, 'Music & Arts', 200.00),
--          (6, 'Web Sockets', 'Real-time messaging', NULL, 'IT & Programming', 200.00),
--          (7, 'Memory Techniques', 'Better retention', NULL, 'Education', 200.00),
--          (8, 'Concurrency', 'Handling tasks', NULL, 'IT & Programming', 200.00),
--          (1, 'Creative Pottery', 'Express yourself', NULL, 'Music & Arts', 200.00),
--          (2, 'Linear Systems', 'Matrix operations', NULL, 'Math & Physics', 200.00),
--          (3, 'Cycling Tour', 'See city on bike', NULL, 'Travel', 200.00),
--          (4, 'Fetch API', 'HTTP requests', NULL, 'IT & Programming', 200.00),
--          (5, 'Markers Drawing', 'Solid colors', NULL, 'Music & Arts', 200.00),
--          (6, 'Server Logs', 'Analysis and alerts', NULL, 'IT & Programming', 200.00),
--          (7, 'Interview Prep', 'Soft skills', NULL, 'Education', 200.00),
--          (8, 'Debugging Tips', 'Solving hard bugs', NULL, 'IT & Programming', 200.00),
--          (1, 'Clay Modeling', 'Character building', NULL, 'Music & Arts', 200.00),
--          (2, 'Geometry proofs', 'Logic steps', NULL, 'Math & Physics', 200.00),
--          (3, 'Tea Tasting', 'Cultural tradition', NULL, 'Travel', 200.00),
--          (4, 'ES6 Modules', 'Importing scripts', NULL, 'IT & Programming', 200.00),
--          (5, 'Still Life', 'Drawing from life', NULL, 'Music & Arts', 200.00),
--          (6, 'Nginx Reverse Proxy', 'Gateway setup', NULL, 'IT & Programming', 200.00),
--          (7, 'Active Listening', 'Better communication', NULL, 'Education', 200.00),
--          (8, 'Software Patterns', 'Design choices', NULL, 'IT & Programming', 200.00),
--          (1, 'Pottery Textures', 'Carving patterns', NULL, 'Music & Arts', 200.00),
--          (2, 'Series and Sequences', 'Math growth', NULL, 'Math & Physics', 200.00),
--          (3, 'Bakery Tour', 'Fresh bread spots', NULL, 'Travel', 200.00),
--          (4, 'Local Storage', 'Browser data', NULL, 'IT & Programming', 200.00),
--          (5, 'Urban Sketching', 'Drawing on streets', NULL, 'Music & Arts', 200.00),
--          (6, 'SSH Access', 'Remote server control', NULL, 'IT & Programming', 200.00),
--          (7, 'Writing Essays', 'Structure and style', NULL, 'Education', 200.00),
--          (8, 'Code Review', 'Team standards', NULL, 'IT & Programming', 200.00),
--          (1, 'Glaze Mixing', 'Chemistry of colors', NULL, 'Music & Arts', 200.00),
--          (2, 'Integral Calculus', 'Calculating area', NULL, 'Math & Physics', 200.00),
--          (3, 'Street Food Tour', 'Local eats', NULL, 'Travel', 200.00),
--          (4, 'Canvas API', 'Drawing in browser', NULL, 'IT & Programming', 200.00),
--          (5, 'Illustration Basics', 'Storytelling', NULL, 'Music & Arts', 200.00),
--          (6, 'Database Migrations', 'Versioning data', NULL, 'IT & Programming', 200.00),
--          (7, 'Negotiation', 'Finding balance', NULL, 'Education', 200.00),
--          (8, 'Clean Architecture', 'Modular software', NULL, 'IT & Programming', 200.00),
--          (1, 'Pottery Masterclass', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL,'Music & Arts', 150.00),
--          (2, 'Calculus Intensive', 'Short math tutorial.', NULL,'Math & Physics',450.00),
--          (3, 'City Tour', 'Short travel tour.', NULL, 'Travel', 80.00),
--          (4, 'React Basics', 'Short coding intro.', NULL,'IT & Programming', 600.00),
--          (5, 'Painting 101', 'Short art class.', NULL,'Music & Arts', 120.00),
--          (6, 'Data Science Intro', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL,'IT & Programming', 350.00),
--          (7, 'Public Speaking', 'Short talk skills.', NULL,'Education', 100.00),
--          (8, 'Algorithms', 'Short coding task.', NULL,'IT & Programming', 500.00),
--          (1, 'Clay Hand-building', 'Short clay class.', NULL,'Music & Arts', 90.00),
--          (2, 'Discrete Math', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.',NULL, 'Math & Physics', 200.00),
--          (3, 'Food Tour', 'Short food guide.',NULL, 'Travel', 150.00),
--          (4, 'CSS Masterclass', 'Short design tips.', NULL,'IT & Programming', 75.00),
--          (5, 'Digital Art', 'Short digital painting.', NULL,'Music & Arts', 250.00),
--          (6, 'Linux Basics', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.',NULL, 'IT & Programming', 180.00),
--          (7, 'Creative Writing', 'Short writing tips.', NULL,'Education', 110.00),
--          (8, 'System Design', 'Short design intro.', NULL,'IT & Programming', 400.00),
--          (1, 'Wheel Throwing', 'Short pottery skills.', NULL,'Music & Arts', 130.00),
--          (2, 'Linear Algebra', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL,'Math & Physics', 220.00),
--          (3, 'Mountain Hiking', 'Short nature trip.', NULL,'Travel', 95.00),
--          (4, 'Node.js Express', 'Short backend course.',NULL, 'IT & Programming', 320.00),
--          (5, 'Sketching Basics', 'Short drawing class.', NULL,'Music & Arts', 60.00),
--          (6, 'SQL Optimization', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL,'IT & Programming', 210.00),
--          (7, 'Time Management', 'Short productivity.', NULL,'Education', 45.00),
--          (8, 'Game Dev Unity', 'Short game creation.', NULL,'IT & Programming', 450.00),
--          (1, 'Ceramics Glazing', 'Short finishing tips.', NULL,'Music & Arts', 110.00),
--          (2, 'Probability', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL,'Math & Physics', 190.00),
--          (3, 'Night Tour', 'Short city night.', NULL,'Travel', 70.00),
--          (4, 'JavaScript ES6', 'Short modern JS.',NULL, 'IT & Programming', 280.00),
--          (5, 'Watercolor Art', 'Short paint lesson.',NULL, 'Music & Arts', 95.00),
--          (6, 'AWS Cloud Intro', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL,'IT & Programming', 380.00),
--          (7, 'Literary Analysis', 'Short book review.', NULL,'Education', 85.00),
--          (8, 'Game Physics', 'Short game math.',NULL, 'IT & Programming', 310.00),
--          (1, 'Kiln Basics', 'Short kiln usage.', NULL,'Music & Arts', 140.00),
--          (2, 'Statistics 101', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL,'Math & Physics', 170.00),
--          (3, 'Wine Tasting', 'Short local wine.',NULL, 'Travel', 120.00),
--          (4, 'React Hooks', 'Short react guide.', NULL,'IT & Programming', 330.00),
--          (5, 'Digital Illustration', 'Short digital art.', NULL,'Music & Arts', 290.00),
--          (6, 'Cybersecurity', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL,'IT & Programming', 410.00),
--          (7, 'Public Speaking', 'Short vocal practice.', NULL,'Education', 90.00),
--          (8, 'Machine Learning', 'Short ML basics.', NULL,'IT & Programming', 520.00),
--          (1, 'Sculpting', 'Short clay form.',NULL, 'Music & Arts', 160.00),
--          (2, 'Geometry Review', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL,'Math & Physics', 150.00),
--          (3, 'City Photography', 'Short camera tour.', NULL,'Travel', 110.00),
--          (4, 'Node.js API', 'Short server build.',NULL, 'IT & Programming', 250.00),
--          (5, 'Charcoal Drawing', 'Short art basics.',NULL, 'Music & Arts', 70.00),
--          (6, 'Git Workshop', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL,'IT & Programming', 90.00),
--          (7, 'Business English', 'Short writing course.',NULL, 'Education', 130.00),
--          (8, 'System Design', 'Short arch course.', NULL,'IT & Programming', 420.00),
--          (1, 'Advanced Throwing', 'Short clay skill.', NULL,'Music & Arts', 190.00),
--          (2, 'Statistics Basics', 'Short stats review.',NULL, 'Math & Physics', 160.00);
--
--
-- INSERT INTO bookings(taker_id, service_id) VALUES
--                                                (1, 3),
--                                                (4, 1),
--                                                (3, 1),
--                                                (4, 4),
--                                                (6, 4),
--                                                (7, 4),
--                                                (7, 1);
--
-- INSERT INTO favorites (user_id, service_id) VALUES
--                                                 (1, 2),
--                                                 (1, 5),
--                                                 (2, 3);
--






-- ==========================================
-- 1. მომხმარებლები (20 საერთაშორისო იუზერი)
-- ==========================================
INSERT INTO users (first_name, last_name, email, password_hash, about_me, image_path, is_enabled, verification_code) VALUES
                                                                                                                         ('Amara', 'Okonkwo', 'amara.o@example.com', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Architectural designer based in Lagos. I draw inspiration from the vibrant textures of Nigerian street life and sustainable urban planning. When I am not drafting blueprints, I am likely exploring local art galleries or teaching workshops on bamboo construction techniques to architecture students.', NULL, 1, NULL),
                                                                                                                         ('Hiroshi', 'Tanaka', 'h.tanaka@example.jp', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Systems engineer from Kyoto with a passion for vintage mechanical watches and modular synthesis. I spend my weekends restoring antique clocks and experimenting with ambient soundscapes in my home studio.', NULL, 1, NULL),
                                                                                                                         ('Elena', 'Petrova', 'elena.pet@example.bg', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Botanist and documentary photographer. I spend most of my year trekking through the Balkan mountains documenting rare alpine flora. I am deeply concerned with climate change and often speak at universities about preservation efforts. Looking for interesting travel companions for my next expedition.', NULL, 1, NULL),
                                                                                                                         ('Mateo', 'Fernández', 'mateo.f@example.ar', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Professional barista in Buenos Aires. I take coffee science very seriously—everything from bean origin to water mineral content. When the cafe closes, I play jazz bass in a local ensemble.', NULL, 1, NULL),
                                                                                                                         ('Sanaa', 'Al-Mansour', 'sanaa.am@example.ae', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Digital marketing strategist with a focus on tech startups. I moved to Dubai three years ago and love the fast-paced energy. I enjoy marathon training and finding the best hidden food spots in the city.', NULL, 1, NULL),
                                                                                                                         ('Lars', 'Jensen', 'lars.j@example.dk', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Furniture designer from Copenhagen. Minimalism is my philosophy, but I believe every object should tell a story. I spend my winters cross-country skiing and my summers restoring a wooden sailboat.', NULL, 1, NULL),
                                                                                                                         ('Fatoumata', 'Diop', 'f.diop@example.sn', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Human rights lawyer working in Dakar. My life is balanced between intense courtroom debates and quiet evenings practicing traditional Senegalese weaving.', NULL, 1, NULL),
                                                                                                                         ('Alessandro', 'Rossi', 'ale.rossi@example.it', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Culinary arts student in Florence. I am currently obsessing over the perfect sourdough fermentation process. On Sundays, I volunteer at a local community kitchen.', NULL, 1, NULL),
                                                                                                                         ('Mei', 'Lin', 'mei.lin.dev@example.cn', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Full-stack developer. I love solving complex algorithmic puzzles and contributing to open-source climate data projects. I am a huge fan of retro science fiction and black coffee.', NULL, 1, NULL),
                                                                                                                         ('Kofi', 'Mensah', 'kofi.m@example.gh', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Journalist covering environmental issues across West Africa. I believe stories have the power to change policies. I am an amateur ornithologist and spend my mornings birdwatching in the wetlands.', NULL, 1, NULL),
                                                                                                                         ('Ingrid', 'Berg', 'ingrid.b@example.no', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Environmental geologist specializing in glacier movement. I have lived in remote field stations for months at a time, but I always come back for good books and strong dark chocolate.', NULL, 1, NULL),
                                                                                                                         ('Arjun', 'Patel', 'arjun.p@example.in', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Astrophysics PhD student. When I am not mapping stars, I am teaching myself how to play the tabla. I love collaborative science projects and late-night philosophical discussions.', NULL, 1, NULL),
                                                                                                                         ('Zeynep', 'Yilmaz', 'zeynep.y@example.tr', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Graphic designer based in Istanbul. I work with traditional Anatolian patterns merged with modern UI/UX design. Passionate about sustainable fashion and local handicraft preservation.', NULL, 1, NULL),
                                                                                                                         ('Javier', 'Silva', 'javier.s@example.cl', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Astronomer and avid climber. I split my time between the observatories in the Atacama Desert and scaling the peaks of the Andes. Nothing beats the view of the Milky Way from a mountain bivouac.', NULL, 1, NULL),
                                                                                                                         ('Chloe', 'Dubois', 'chloe.d@example.fr', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Restoration expert for historical paintings in Paris. I enjoy the painstaking process of uncovering centuries-old layers of paint. I spend my spare time cycling through the French countryside.', NULL, 1, NULL),
                                                                                                                         ('Viktor', 'Novak', 'vik.novak@example.cz', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Independent filmmaker and photographer. I focus on urban decay and social change. I am usually carrying three different cameras and a notebook for screenplays.', NULL, 1, NULL),
                                                                                                                         ('Yuki', 'Sato', 'yuki.sato@example.jp', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Library science researcher. My life is essentially an archive of rare manuscripts and lost stories. I am currently learning Latin and enjoy quiet afternoons in historical archives.', NULL, 1, NULL),
                                                                                                                         ('Sofia', 'Müller', 'sofia.m@example.de', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Data analyst by day, professional urban gardener by night. I am obsessed with vertical farming and making Berlin a greener city, one balcony at a time. I love dogs and sci-fi podcasts.', NULL, 1, NULL),
                                                                                                                         ('Hamza', 'Ibrahim', 'hamza.i@example.eg', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'History teacher and amateur archaeologist. I spend my weekends near the Nile trying to map unrecorded burial sites. I am passionate about keeping history alive for the younger generation.', NULL, 1, NULL),
                                                                                                                         ('Lucia', 'Gomes', 'lucia.g@example.br', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Marine biologist focused on reef conservation in Brazil. My work involves diving, data collection, and fighting for ocean protection. When on land, I enjoy capoeira and healthy cooking.', NULL, 1, NULL);

-- ==========================================
-- 2. სერვისები
-- ==========================================
INSERT INTO services (provider_id, title, bio, image_path, category, price) VALUES
                                                                                (1, 'Introduction to Sustainable Architecture', 'In this comprehensive workshop, we explore the integration of eco-friendly materials into modern home design. We will look at natural ventilation strategies, solar orientation, and the use of reclaimed materials to reduce your carbon footprint while maintaining aesthetic beauty.', NULL, 'arch', 75.00),
                                                                                (1, 'Lagos Urban Planning Tour', 'Join me for an immersive walking tour of Lagos, where we analyze the intersection of traditional architecture and rapid urbanization. We will visit key sites that showcase how sustainable design is slowly transforming the city landscape.', NULL, 'touring', 40.00),
                                                                                (2, 'Mastering C# for Unity Development', 'From absolute beginner to building your first 2D platformer. This course covers core C# syntax, object-oriented programming principles, and how they apply specifically to the Unity game engine. Perfect for those looking to start their career in game dev.', NULL, 'game development', 120.00),
                                                                                (2, 'Vintage Watch Restoration Basics', 'A delicate, meditative dive into the world of horology. Learn how to safely open, clean, and re-oil antique mechanical movements. I provide the tools and guidance; you bring the patience.', NULL, 'watch restoration', 90.00),
                                                                                (3, 'Alpine Flora Identification Field Trip', 'Spend a day with me in the mountains learning how to identify endemic plant species. We will discuss the ecosystem, the challenges of high-altitude life, and how climate change is affecting these fragile habitats.', NULL, 'trip', 60.00),
                                                                                (3, 'Nature Photography Masterclass', 'Capture the wilderness like a pro. This course covers composition, lighting in diverse environments, and how to tell a story through botanical photography. Bring your camera and sturdy hiking boots.', NULL, 'photography', 55.00),
                                                                                (4, 'The Science of Espresso Extraction', 'Beyond the button press. Learn about grind size, water pressure, puck preparation, and the chemistry behind the perfect shot. We will dial in a coffee together until it tastes balanced and sweet.', NULL, 'coffe making classes', 45.00),
                                                                                (4, 'Jazz Bass Fundamentals', 'A beginner-friendly guide to walking bass lines and jazz improvisation. We will cover standard chord progressions, rhythm, and how to find your groove within an ensemble.', NULL, 'learn jazz culture', 35.00),
                                                                                (5, 'Tech Startup Branding Strategy', 'How to define your voice in a crowded market. We will go over audience segmentation, content strategy, and how to build a brand identity that resonates with early adopters in the tech space.', NULL, 'startup branding', 150.00),
                                                                                (5, 'Professional Social Media Audit', 'Struggling to gain traction? I will provide a deep dive into your current digital presence, offering actionable insights on how to improve your engagement and conversion rates.', NULL, 'social media', 85.00),
                                                                                (6, 'Danish Modern Furniture Workshop', 'Learn to build a simple, elegant side table using traditional joinery techniques. We emphasize functionality, clean lines, and high-quality craftsmanship.', NULL, 'furniture', 200.00),
                                                                                (6, 'Introduction to Nordic Woodworking', 'Learn the basics of hand-tool woodworking. We will cover timber selection, sharpening your chisels, and the basics of creating durable, beautiful joints that last a lifetime.', NULL, 'woodworking', 110.00),
                                                                                (7, 'Introduction to Civil Rights Advocacy', 'A foundational course on understanding your rights and how to navigate legal systems. We will look at case studies from around the world and discuss how to engage in ethical advocacy.', NULL, 'civil rights', 65.00),
                                                                                (7, 'Traditional Weaving Workshop', 'A workshop on Senegalese weaving techniques. This is a chance to learn a beautiful, ancient craft while we discuss the history and cultural significance of textile arts in West Africa.', NULL, 'weaving', 50.00),
                                                                                (8, 'Authentic Sourdough Baking', 'Forget store-bought loaves. Learn how to create, feed, and maintain your own sourdough starter, and master the art of the perfect, crusty artisan loaf.', NULL, 'cooking', 40.00),
                                                                                (8, 'Italian Home Cooking Secrets', 'Simple, high-quality ingredients made right. We will focus on the fundamentals of handmade pasta, perfect marinara, and classic desserts that impress every time.', NULL, 'cooking', 55.00),
                                                                                (1, 'Pottery Basics', 'Hands-on pottery workshop', NULL, 'Arts', 200.00),
                                                                                (2, 'Calculus Tutoring', 'Advanced math help', NULL, 'Math & Physics', 200.00),
                                                                                (3, 'Tbilisi City Tour', 'Customized local tours', NULL, 'Travel', 200.00),
                                                                                (4, 'Programming Basics', 'Intro to coding', NULL, 'IT & Programming', 200.00),
                                                                                (5, 'Painting Class', 'Learn to paint landscapes', NULL, 'Music & Arts', 200.00),
                                                                                (6, 'Python Workshop', 'Backend development', NULL, 'IT & Programming', 200.00),
                                                                                (7, 'Language Lessons', 'Learn Georgian quickly', NULL, 'Education', 200.00),
                                                                                (8, 'Data Structures', 'Competitive programming prep', NULL, 'IT & Programming', 200.00);
INSERT INTO favorites (user_id, service_id) VALUES
                                                (1, 2),
                                                (1, 5),
                                                (2, 3);