INSERT INTO users (first_name, last_name, email, password_hash, about_me, image_path, is_enabled, verification_code) VALUES
                                                                                                                         ('Amara', 'Okonkwo', 'amara.o@example.com', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Architectural designer based in Lagos. I draw inspiration from the vibrant textures of Nigerian street life and sustainable urban planning. When I am not drafting blueprints, I am likely exploring local art galleries or teaching workshops on bamboo construction techniques to architecture students.', NULL, 1, NULL),
                                                                                                                         ('Hiroshi', 'Tanaka', 'h.tanaka@example.jp', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Systems engineer from Kyoto with a passion for vintage mechanical watches and modular synthesis. I spend my weekends restoring antique clocks and experimenting with ambient soundscapes in my home studio.', NULL, 1, NULL),
                                                                                                                         ('Elena', 'Petrova', 'elena.pet@example.bg', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Botanist and documentary photographer. I spend most of my year trekking through the Balkan mountains documenting rare alpine flora. I am deeply concerned with climate change and often speak at universities about preservation efforts. Looking for interesting travel companions for my next expedition.', NULL, 1, NULL),
                                                                                                                         ('Mateo', 'Fernández', 'mateo.f@example.ar', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Professional barista in Buenos Aires. I take coffee science very seriously—everything from bean origin to water mineral content. When the cafe closes, I play jazz bass in a local ensemble.', NULL, 1, NULL),
                                                                                                                         ('Sanaa', 'Al-Mansour', 'sanaa.am@example.ae', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Digital marketing strategist with a focus on tech startups. I moved to Dubai three years ago and love the fast-paced energy. I enjoy marathon training and finding the best hidden food spots in the city.', NULL, 1, NULL),
                                                                                                                         ('Lars', 'Jensen', 'lars.j@example.dk', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Furniture designer from Copenhagen. Minimalism is my philosophy, but I believe every object should tell a story. I spend my winters cross-country skiing and my summers restoring a wooden sailboat.', NULL, 1, NULL),
                                                                                                                         ('Fatoumata', 'Diop', 'f.diop@example.sn', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Human rights lawyer working in Dakar. My life is balanced between intense courtroom debates and quiet evenings practicing traditional Senegalese weaving.', NULL, 1, NULL),
                                                                                                                         ('Alessandro', 'Rossi', 'ale.rossi@example.it', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Culinary arts student in Florence. I am currently obsessing over the perfect sourdough fermentation process. On Sundays, I volunteer at a local community kitchen.', NULL, 1, NULL),
                                                                                                                         ('Mei', 'Lin', 'mei.lin.dev@example.cn', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Full-stack developer. I love solving complex algorithmic puzzles and contributing to open-source climate data projects. I am a huge fan of retro science fiction and black coffee.', NULL, 1, NULL),
                                                                                                                         ('Kofi', 'Mensah', 'kofi.m@example.gh', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Journalist covering environmental issues across West Africa. I believe stories have the power to change policies. I am an amateur ornithologist and spend my mornings birdwatching in the wetlands.', NULL, 1, NULL),
                                                                                                                         ('Ingrid', 'Berg', 'ingrid.b@example.no', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Environmental geologist specializing in glacier movement. I have lived in remote field stations for months at a time, but I always come back for good books and strong dark chocolate.', NULL, 1, NULL),
                                                                                                                         ('Arjun', 'Patel', 'arjun.p@example.in', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Astrophysics PhD student. When I am not mapping stars, I am teaching myself how to play the tabla. I love collaborative science projects and late-night philosophical discussions.', NULL, 1, NULL),
                                                                                                                         ('Zeynep', 'Yilmaz', 'zeynep.y@example.tr', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Graphic designer based in Istanbul. I work with traditional Anatolian patterns merged with modern UI/UX design. Passionate about sustainable fashion and local handicraft preservation.', NULL, 1, NULL),
                                                                                                                         ('Javier', 'Silva', 'javier.s@example.cl', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Astronomer and avid climber. I split my time between the observatories in the Atacama Desert and scaling the peaks of the Andes. Nothing beats the view of the Milky Way from a mountain bivouac.', NULL, 1, NULL),
                                                                                                                         ('Chloe', 'Dubois', 'chloe.d@example.fr', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Restoration expert for historical paintings in Paris. I enjoy the painstaking process of uncovering centuries-old layers of paint. I spend my spare time cycling through the French countryside.', NULL, 1, NULL),
                                                                                                                         ('Viktor', 'Novak', 'vik.novak@example.cz', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Independent filmmaker and photographer. I focus on urban decay and social change. I am usually carrying three different cameras and a notebook for screenplays.', NULL, 1, NULL),
                                                                                                                         ('Yuki', 'Sato', 'yuki.sato@example.jp', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Library science researcher. My life is essentially an archive of rare manuscripts and lost stories. I am currently learning Latin and enjoy quiet afternoons in historical archives.', NULL, 1, NULL),
                                                                                                                         ('Sofia', 'Müller', 'sofia.m@example.de', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Data analyst by day, professional urban gardener by night. I am obsessed with vertical farming and making Berlin a greener city, one balcony at a time. I love dogs and sci-fi podcasts.', NULL, 1, NULL),
                                                                                                                         ('Hamza', 'Ibrahim', 'hamza.i@example.eg', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'History teacher and amateur archaeologist. I spend my weekends near the Nile trying to map unrecorded burial sites. I am passionate about keeping history alive for the younger generation.', NULL, 1, NULL),
                                                                                                                         ('Lucia', 'Gomes', 'lucia.g@example.br', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Marine biologist focused on reef conservation in Brazil. My work involves diving, data collection, and fighting for ocean protection. When on land, I enjoy capoeira and healthy cooking.', NULL, 1, NULL);


INSERT INTO services (provider_id, title, bio, image_path, price, category) VALUES
(1, 'Introduction to Sustainable Architecture', 'In this comprehensive workshop, we explore the integration of eco-friendly materials into modern home design. We will look at natural ventilation strategies, solar orientation, and the use of reclaimed materials to reduce your carbon footprint while maintaining aesthetic beauty.', 'https://fastly.picsum.photos/id/288/200/200.jpg?hmac=PrR6Ld35xhRNiCKOIS-dmUjGl-L-3ylEddVJrdwCAHw', 75.00, 'arch'),
(1, 'Lagos Urban Planning Tour', 'Join me for an immersive walking tour of Lagos, where we analyze the intersection of traditional architecture and rapid urbanization. We will visit key sites that showcase how sustainable design is slowly transforming the city landscape.', 'https://fastly.picsum.photos/id/434/200/200.jpg?hmac=XGqvfpLw0rMcPyD8jH0Ta9jFlmmXrnpbu7IcMOORrQQ', 40.00, 'touring'),

(2, 'Mastering C# for Unity Development', 'From absolute beginner to building your first 2D platformer. This course covers core C# syntax, object-oriented programming principles, and how they apply specifically to the Unity game engine. Perfect for those looking to start their career in game dev.', 'https://fastly.picsum.photos/id/0/200/200.jpg?hmac=RZmZI0kb9l_aRWHFyOZUGyc8xsyV30HOJX8a4wuHWkA', 120.00, 'game development'),
(2, 'Vintage Watch Restoration Basics', 'A delicate, meditative dive into the world of horology. Learn how to safely open, clean, and re-oil antique mechanical movements. I provide the tools and guidance; you bring the patience.', 'https://images.squarespace-cdn.com/content/v1/53fce39fe4b0e51709f79b46/cc28b985-fc11-449a-8aa3-e28a48a535d0/PXL_20230907_151219732.jpg', 90.00, 'watches'),

(3, 'Alpine Flora Identification Field Trip', 'Spend a day with me in the mountains learning how to identify endemic plant species. We will discuss the ecosystem, the challenges of high-altitude life, and how climate change is affecting these fragile habitats.', 'https://fastly.picsum.photos/id/519/200/200.jpg?hmac=7MwcBjyXrRX5GB6GuDATVm_6MFDRmZaSK7r5-jqDNS0', 60.00, 'trip'),
(3, 'Nature Photography Masterclass', 'Capture the wilderness like a pro. This course covers composition, lighting in diverse environments, and how to tell a story through botanical photography. Bring your camera and sturdy hiking boots.', NULL, 55.00, 'nature'),

(4, 'The Science of Espresso Extraction', 'Beyond the button press. Learn about grind size, water pressure, puck preparation, and the chemistry behind the perfect shot. We will dial in a coffee together until it tastes balanced and sweet.', NULL, 45.00, 'coffee'),
(4, 'Jazz Bass Fundamentals', 'A beginner-friendly guide to walking bass lines and jazz improvisation. We will cover standard chord progressions, rhythm, and how to find your groove within an ensemble.', NULL, 35.00, 'jazz classes'),

(5, 'Tech Startup Branding Strategy', 'How to define your voice in a crowded market. We will go over audience segmentation, content strategy, and how to build a brand identity that resonates with early adopters in the tech space.', NULL, 150.00, 'startup branding'),
(5, 'Professional Social Media Audit', 'Struggling to gain traction? I will provide a deep dive into your current digital presence, offering actionable insights on how to improve your engagement and conversion rates.', NULL, 85.00, 'social media'),

(6, 'Danish Modern Furniture Workshop', 'Learn to build a simple, elegant side table using traditional joinery techniques. We emphasize functionality, clean lines, and high-quality craftsmanship.', NULL, 200.00, 'furniture'),
(6, 'Introduction to Nordic Woodworking', 'Learn the basics of hand-tool woodworking. We will cover timber selection, sharpening your chisels, and the basics of creating durable, beautiful joints that last a lifetime.', NULL, 110.00, 'woodworking'),

(7, 'Introduction to Civil Rights Advocacy', 'A foundational course on understanding your rights and how to navigate legal systems. We will look at case studies from around the world and discuss how to engage in ethical advocacy.', NULL, 65.00, 'civil rights'),
(7, 'Traditional Weaving Workshop', 'A workshop on Senegalese weaving techniques. This is a chance to learn a beautiful, ancient craft while we discuss the history and cultural significance of textile arts in West Africa.', NULL, 50.00, 'workshop'),

(8, 'Authentic Sourdough Baking', 'Forget store-bought loaves. Learn how to create, feed, and maintain your own sourdough starter, and master the art of the perfect, crusty artisan loaf.', NULL, 40.00, 'baking'),
(8, 'Italian Home Cooking Secrets', 'Simple, high-quality ingredients made right. We will focus on the fundamentals of handmade pasta, perfect marinara, and classic desserts that impress every time.', NULL, 55.00, 'cooking'),

(5, 'Painting Class', 'Learn to paint landscapes', NULL, 200.00, 'Music & Arts'),
(6, 'Python Workshop', 'Backend development', NULL, 200.00, 'IT & Programming'),
(7, 'Language Lessons', 'Learn Georgian quickly', NULL, 200.00, 'Education'),
(8, 'Data Structures', 'Competitive programming prep', NULL, 200.00, 'IT & Programming'),
(1, 'Ceramics Design', 'Advanced pottery techniques', NULL, 200.00, 'Music & Arts'),
(2, 'Linear Algebra', 'University level math', NULL, 200.00, 'Math & Physics'),
(3, 'Gastronomic Tour', 'Explore Georgian food', NULL, 200.00, 'Travel'),
(4, 'Web Development', 'Full stack basics', NULL, 200.00, 'IT & Programming'),
(5, 'Sketching 101', 'Foundations of drawing', NULL, 200.00, 'Music & Arts'),
(6, 'Database Design', 'SQL and NoSQL', NULL, 200.00, 'IT & Programming'),
(7, 'History of Tbilisi', 'A deep dive into history', NULL, 200.00, 'Education'),
(8, 'Algorithm Design', 'Optimization techniques', NULL, 200.00, 'IT & Programming'),
(1, 'Glazing Techniques', 'Final touches in pottery', NULL, 200.00, 'Music & Arts'),
(2, 'Differential Equations', 'Solving complex problems', NULL, 200.00, 'Math & Physics'),
(3, 'Mountain Hiking', 'Day trip in the Caucasus', NULL, 200.00, 'Travel'),
(4, 'JavaScript ES6', 'Modern web scripting', NULL, 200.00, 'IT & Programming'),
(5, 'Watercolor Painting', 'Beginner watercolor skills', NULL, 200.00, 'Music & Arts'),
(6, 'Cloud Infrastructure', 'Introduction to AWS', NULL, 200.00, 'IT & Programming'),
(7, 'Literary Analysis', 'Reading classic literature', NULL, 200.00, 'Education'),
(8, 'Game Architecture', 'Advanced unity topics', NULL, 200.00, 'IT & Programming'),
(1, 'Kiln Operation', 'Understanding firing', NULL, 200.00, 'Music & Arts'),
(2, 'Probability Theory', 'Fundamentals of chance', NULL, 200.00, 'Math & Physics'),
(3, 'Wine Tasting Tour', 'Local winery visit', NULL, 200.00, 'Travel'),
(4, 'React Framework', 'Building interfaces', NULL, 200.00, 'IT & Programming'),
(5, 'Digital Illustration', 'Tablets and software', NULL, 200.00, 'Music & Arts'),
(6, 'Security Basics', 'Web vulnerability audit', NULL, 200.00, 'IT & Programming'),
(7, 'Public Speaking', 'Build your confidence', NULL, 200.00, 'Education'),
(8, 'Machine Learning', 'Intro to neural networks', NULL, 200.00, 'IT & Programming'),
(1, 'Sculpting Fundamentals', 'Modeling clay shapes', NULL, 200.00, 'Music & Arts'),
(2, 'Discrete Mathematics', 'Logic for computer science', NULL, 200.00, 'Math & Physics'),
(3, 'City Photography', 'Best spots in Tbilisi', NULL, 200.00, 'Travel'),
(4, 'Node.js Basics', 'Server-side javascript', NULL, 200.00, 'IT & Programming'),
(5, 'Charcoal Drawing', 'Light and shadow', NULL, 200.00, 'Music & Arts'),
(6, 'Git Workshop', 'Version control mastery', NULL, 200.00, 'IT & Programming'),
(7, 'Business English', 'Professional writing', NULL, 200.00, 'Education'),
(8, 'System Design', 'Scalable architecture', NULL, 200.00, 'IT & Programming'),
(1, 'Advanced Wheel Throwing', 'Challenging shapes', NULL, 200.00, 'Music & Arts'),
(2, 'Statistics 101', 'Data analysis basics', NULL, 200.00, 'Math & Physics'),
(3, 'Art Gallery Tour', 'Visit local exhibitions', NULL, 200.00, 'Travel'),
(4, 'CSS Layouts', 'Flexbox and Grid', NULL, 200.00, 'IT & Programming'),
(5, 'Oil Painting', 'Canvas techniques', NULL, 200.00, 'Music & Arts'),
(6, 'REST API Design', 'Standardized endpoints', NULL, 200.00, 'IT & Programming'),
(7, 'Creative Writing', 'Developing stories', NULL, 200.00, 'Education'),
(8, 'Data Science Intro', 'Pandas and NumPy', NULL, 200.00, 'IT & Programming'),
(1, 'Pottery Decoration', 'Painting on ceramics', NULL, 200.00, 'Music & Arts'),
(2, 'Number Theory', 'Fascinating patterns', NULL, 200.00, 'Math & Physics'),
(3, 'Hidden Tbilisi', 'Secret courtyard tour', NULL, 200.00, 'Travel'),
(4, 'TypeScript Basics', 'Strongly typed code', NULL, 200.00, 'IT & Programming'),
(5, 'Printmaking Workshop', 'Creating patterns', NULL, 200.00, 'Music & Arts'),
(6, 'Docker Essentials', 'Containerizing apps', NULL, 200.00, 'IT & Programming'),
(7, 'Financial Literacy', 'Personal finance guide', NULL, 200.00, 'Education'),
(8, 'Backend Scaling', 'Distributed systems', NULL, 200.00, 'IT & Programming'),
(1, 'Hand-building Clay', 'Coil and slab methods', NULL, 200.00, 'Music & Arts'),
(2, 'Geometry Review', 'Shapes and measurements', NULL, 200.00, 'Math & Physics'),
(3, 'Old Town Architecture', 'Historical tour', NULL, 200.00, 'Travel'),
(4, 'Responsive Design', 'Mobile-first approach', NULL, 200.00, 'IT & Programming'),
(5, 'Portrait Drawing', 'Face structure', NULL, 200.00, 'Music & Arts'),
(6, 'Linux Commands', 'Terminal proficiency', NULL, 200.00, 'IT & Programming'),
(7, 'Time Management', 'Boost your productivity', NULL, 200.00, 'Education'),
(8, 'Python Data Scraping', 'Gathering web data', NULL, 200.00, 'IT & Programming'),
(1, 'Clay Preparation', 'Processing raw material', NULL, 200.00, 'Music & Arts'),
(2, 'Trigonometry', 'Angles and waves', NULL, 200.00, 'Math & Physics'),
(3, 'Night Tour', 'Tbilisi at night', NULL, 200.00, 'Travel'),
(4, 'Bootstrap Framework', 'Speedy UI design', NULL, 200.00, 'IT & Programming'),
(5, 'Acrylic Painting', 'Modern techniques', NULL, 200.00, 'Music & Arts'),
(6, 'API Testing', 'Postman for developers', NULL, 200.00, 'IT & Programming'),
(7, 'Debate Skills', 'Critical thinking', NULL, 200.00, 'Education'),
(8, 'Unit Testing', 'Writing reliable code', NULL, 200.00, 'IT & Programming'),
(1, 'Pottery Glazing', 'Colors and textures', NULL, 200.00, 'Music & Arts'),
(2, 'Math Logic', 'Formal proofs', NULL, 200.00, 'Math & Physics'),
(3, 'Village Day Trip', 'Near city getaway', NULL, 200.00, 'Travel'),
(4, 'SASS/SCSS', 'Efficient stylesheets', NULL, 200.00, 'IT & Programming'),
(5, 'Colored Pencils', 'Drawing textures', NULL, 200.00, 'Music & Arts'),
(6, 'Shell Scripting', 'Bash automation', NULL, 200.00, 'IT & Programming'),
(7, 'Effective Study', 'Learning techniques', NULL, 200.00, 'Education'),
(8, 'Game Physics', 'Intro to mechanics', NULL, 200.00, 'IT & Programming'),
(1, 'Pottery Molds', 'Creating copies', NULL, 200.00, 'Music & Arts'),
(2, 'Advanced Algebra', 'Polynomails and roots', NULL, 200.00, 'Math & Physics'),
(3, 'Local Markets Tour', 'Explore food hubs', NULL, 200.00, 'Travel'),
(4, 'Tailwind CSS', 'Utility-first styling', NULL, 200.00, 'IT & Programming'),
(5, 'Perspective Drawing', '3D on 2D space', NULL, 200.00, 'Music & Arts'),
(6, 'SQL Optimization', 'Fast database queries', NULL, 200.00, 'IT & Programming'),
(1, 'Pottery Masterclass', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 150.00, 'Music & Arts'),
(2, 'Calculus Intensive', 'Short math tutorial.', NULL, 450.00, 'Math & Physics'),
(3, 'City Tour', 'Short travel tour.', NULL, 80.00, 'Travel'),
(4, 'React Basics', 'Short coding intro.', NULL, 600.00, 'IT & Programming'),
(5, 'Painting 101', 'Short art class.', NULL, 120.00, 'Music & Arts'),
(6, 'Data Science Intro', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 350.00, 'IT & Programming'),
(7, 'Public Speaking', 'Short talk skills.', NULL, 100.00, 'Education'),
(8, 'Algorithms', 'Short coding task.', NULL, 500.00, 'IT & Programming'),
(1, 'Clay Hand-building', 'Short clay class.', NULL, 90.00, 'Music & Arts'),
(2, 'Discrete Math', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 200.00, 'Math & Physics'),
(3, 'Food Tour', 'Short food guide.', NULL, 150.00, 'Travel'),
(4, 'CSS Masterclass', 'Short design tips.', NULL, 75.00, 'IT & Programming'),
(5, 'Digital Art', 'Short digital painting.', NULL, 250.00, 'Music & Arts'),
(6, 'Linux Basics', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 180.00, 'IT & Programming'),
(7, 'Creative Writing', 'Short writing tips.', NULL, 110.00, 'Education'),
(8, 'System Design', 'Short design intro.', NULL, 400.00, 'IT & Programming'),
(1, 'Wheel Throwing', 'Short pottery skills.', NULL, 130.00, 'Music & Arts'),
(2, 'Linear Algebra', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 220.00, 'Math & Physics'),
(3, 'Mountain Hiking', 'Short nature trip.', NULL, 95.00, 'Travel'),
(4, 'Node.js Express', 'Short backend course.', NULL, 320.00, 'IT & Programming'),
(5, 'Sketching Basics', 'Short drawing class.', NULL, 60.00, 'Music & Arts'),
(6, 'SQL Optimization', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 210.00, 'IT & Programming'),
(7, 'Time Management', 'Short productivity.', NULL, 45.00, 'Education'),
(8, 'Game Dev Unity', 'Short game creation.', NULL, 450.00, 'IT & Programming'),
(1, 'Ceramics Glazing', 'Short finishing tips.', NULL, 110.00, 'Music & Arts'),
(2, 'Probability', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 190.00, 'Math & Physics'),
(3, 'Night Tour', 'Short city night.', NULL, 70.00, 'Travel'),
(4, 'JavaScript ES6', 'Short modern JS.', NULL, 280.00, 'IT & Programming'),
(5, 'Watercolor Art', 'Short paint lesson.', NULL, 95.00, 'Music & Arts'),
(6, 'AWS Cloud Intro', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 380.00, 'IT & Programming'),
(7, 'Literary Analysis', 'Short book review.', NULL, 85.00, 'Education'),
(8, 'Game Physics', 'Short game math.', NULL, 310.00, 'IT & Programming'),
(1, 'Kiln Basics', 'Short kiln usage.', NULL, 140.00, 'Music & Arts'),
(2, 'Statistics 101', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 170.00, 'Math & Physics'),
(3, 'Wine Tasting', 'Short local wine.', NULL, 120.00, 'Travel'),
(4, 'React Hooks', 'Short react guide.', NULL, 330.00, 'IT & Programming'),
(5, 'Digital Illustration', 'Short digital art.', NULL, 290.00, 'Music & Arts'),
(6, 'Cybersecurity', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 410.00, 'IT & Programming'),
(7, 'Public Speaking', 'Short vocal practice.', NULL, 90.00, 'Education'),
(8, 'Machine Learning', 'Short ML basics.', NULL, 520.00, 'IT & Programming'),
(1, 'Sculpting', 'Short clay form.', NULL, 160.00, 'Music & Arts'),
(2, 'Geometry Review', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 150.00, 'Math & Physics'),
(3, 'City Photography', 'Short camera tour.', NULL, 110.00, 'Travel'),
(4, 'Node.js API', 'Short server build.', NULL, 250.00, 'IT & Programming'),
(5, 'Charcoal Drawing', 'Short art basics.', NULL, 70.00, 'Music & Arts'),
(6, 'Git Workshop', 'This is an exceptionally long bio description intended for testing the Read More functionality. It contains a lot of text to ensure the card expands correctly and looks good in the grid layout.', NULL, 90.00, 'IT & Programming'),
(7, 'Business English', 'Short writing course.', NULL, 130.00, 'Education'),
(8, 'System Design', 'Short arch course.', NULL, 420.00, 'IT & Programming'),
(1, 'Advanced Throwing', 'Short clay skill.', NULL, 190.00, 'Music & Arts'),
(2, 'Statistics Basics', 'Short stats review.', NULL, 160.00, 'Math & Physics');

