INSERT INTO users (first_name, last_name, email, password_hash, about_me, image_path, is_enabled, verification_code) VALUES
                                                                                                                         ('Amara', 'Okonkwo', 'amara.o@example.com', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Architectural designer based in Lagos. I draw inspiration from the vibrant textures of Nigerian street life and sustainable urban planning. When I am not drafting blueprints, I am likely exploring local art galleries or teaching workshops on bamboo construction techniques to architecture students.', NULL, 1, NULL),
                                                                                                                         ('Hiroshi', 'Tanaka', 'h.tanaka@example.jp', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Systems engineer from Kyoto with a passion for vintage mechanical watches and modular synthesis. I spend my weekends restoring antique clocks and experimenting with ambient soundscapes in my home studio.', NULL, 1, NULL),
                                                                                                                         ('Elena', 'Petrova', 'elena.pet@example.bg', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Botanist and documentary photographer. I spend most of my year trekking through the Balkan mountains documenting rare alpine flora. I am deeply concerned with climate change and often speak at universities about preservation efforts. Looking for interesting travel companions for my next expedition.', NULL, 1, NULL),
                                                                                                                         ('Mateo', 'Fernández', 'mateo.f@example.ar', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Professional barista in Buenos Aires. I take coffee science very seriously—everything from bean origin to water mineral content. When the cafe closes, I play jazz bass in a local ensemble.', NULL, 1, NULL),
                                                                                                                         ('Sanaa', 'Al-Mansour', 'sanaa.am@example.ae', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Digital marketing strategist with a focus on tech startups. I moved to Dubai three years ago and love the fast-paced energy. I enjoy marathon training and finding the best hidden food spots in the city.', NULL, 1, NULL),
                                                                                                                         ('Lars', 'Jensen', 'lars.j@example.dk', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Furniture designer from Copenhagen. Minimalism is my philosophy, but I believe every object should tell a story. I spend my winters cross-country skiing and my summers restoring a wooden sailboat.', NULL, 1, NULL),
                                                                                                                         ('Fatoumata', 'Diop', 'f.diop@example.sn', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Human rights lawyer working in Dakar. My life is balanced between intense courtroom debates and quiet evenings practicing traditional Senegalese weaving.', NULL, 1, NULL),
                                                                                                                         ('Alessandro', 'Rossi', 'ale.rossi@example.it', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Culinary arts student in Florence. I am currently obsessing over the perfect sourdough fermentation process. On Sundays, I volunteer at a local community kitchen.', NULL, 1, NULL),
                                                                                                                         ('Mei', 'Lin', 'mei.lin.dev@example.cn', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Full-stack developer. I love solving complex algorithmic puzzles and contributing to open-source climate data projects. I am a huge fan of retro science fiction and black coffee.', NULL, 1, NULL),
                                                                                                                         ('Kofi', 'Mensah', 'kofi.m@example.gh', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Journalist covering environmental issues across West Africa. I believe stories have the power to change policies. I am an amateur ornithologist and spend my mornings birdwatching in the wetlands.', NULL, 1, NULL),
                                                                                                                         ('Ingrid', 'Berg', 'ingrid.b@example.no', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Environmental geologist specializing in glacier movement. I have lived in remote field stations for months at a time, but I always come back for good books and strong dark chocolate.', NULL, 1, NULL),
                                                                                                                         ('Arjun', 'Patel', 'arjun.p@example.in', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Astrophysics PhD student. When I am not mapping stars, I am teaching myself how to play the tabla. I love collaborative science projects and late-night philosophical discussions.', NULL, 1, NULL),
                                                                                                                         ('Zeynep', 'Yilmaz', 'zeynep.y@example.tr', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Graphic designer based in Istanbul. I work with traditional Anatolian patterns merged with modern UI/UX design. Passionate about sustainable fashion and local handicraft preservation.', NULL, 1, NULL),
                                                                                                                         ('Javier', 'Silva', 'javier.s@example.cl', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Astronomer and avid climber. I split my time between the observatories in the Atacama Desert and scaling the peaks of the Andes. Nothing beats the view of the Milky Way from a mountain bivouac.', NULL, 1, NULL),
                                                                                                                         ('Chloe', 'Dubois', 'chloe.d@example.fr', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Restoration expert for historical paintings in Paris. I enjoy the painstaking process of uncovering centuries-old layers of paint. I spend my spare time cycling through the French countryside.', NULL, 1, NULL),
                                                                                                                         ('Viktor', 'Novak', 'vik.novak@example.cz', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Independent filmmaker and photographer. I focus on urban decay and social change. I am usually carrying three different cameras and a notebook for screenplays.', NULL, 1, NULL),
                                                                                                                         ('Yuki', 'Sato', 'yuki.sato@example.jp', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Library science researcher. My life is essentially an archive of rare manuscripts and lost stories. I am currently learning Latin and enjoy quiet afternoons in historical archives.', NULL, 1, NULL),
                                                                                                                         ('Sofia', 'Müller', 'sofia.m@example.de', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Data analyst by day, professional urban gardener by night. I am obsessed with vertical farming and making Berlin a greener city, one balcony at a time. I love dogs and sci-fi podcasts.', NULL, 1, NULL),
                                                                                                                         ('Hamza', 'Ibrahim', 'hamza.i@example.eg', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'History teacher and amateur archaeologist. I spend my weekends near the Nile trying to map unrecorded burial sites. I am passionate about keeping history alive for the younger generation.', NULL, 1, NULL),
                                                                                                                         ('Lucia', 'Gomes', 'lucia.g@example.br', '{bcrypt}$2a$10$8QvDfni0jK7iujf14YZkheizru3nZdOAnToEBdQiVh9zMOTkKhZ6G', 'Marine biologist focused on reef conservation in Brazil. My work involves diving, data collection, and fighting for ocean protection. When on land, I enjoy capoeira and healthy cooking.', NULL, 1, NULL);


INSERT INTO services (provider_id, title, bio, image_path, price) VALUES
(1, 'Introduction to Sustainable Architecture', 'In this comprehensive workshop, we explore the integration of eco-friendly materials into modern home design. We will look at natural ventilation strategies, solar orientation, and the use of reclaimed materials to reduce your carbon footprint while maintaining aesthetic beauty.', 'https://fastly.picsum.photos/id/288/200/200.jpg?hmac=PrR6Ld35xhRNiCKOIS-dmUjGl-L-3ylEddVJrdwCAHw', 75.00),
(1, 'Lagos Urban Planning Tour', 'Join me for an immersive walking tour of Lagos, where we analyze the intersection of traditional architecture and rapid urbanization. We will visit key sites that showcase how sustainable design is slowly transforming the city landscape.', 'https://fastly.picsum.photos/id/434/200/200.jpg?hmac=XGqvfpLw0rMcPyD8jH0Ta9jFlmmXrnpbu7IcMOORrQQ', 40.00),

(2, 'Mastering C# for Unity Development', 'From absolute beginner to building your first 2D platformer. This course covers core C# syntax, object-oriented programming principles, and how they apply specifically to the Unity game engine. Perfect for those looking to start their career in game dev.', 'https://fastly.picsum.photos/id/0/200/200.jpg?hmac=RZmZI0kb9l_aRWHFyOZUGyc8xsyV30HOJX8a4wuHWkA', 120.00),
(2, 'Vintage Watch Restoration Basics', 'A delicate, meditative dive into the world of horology. Learn how to safely open, clean, and re-oil antique mechanical movements. I provide the tools and guidance; you bring the patience.', 'https://images.squarespace-cdn.com/content/v1/53fce39fe4b0e51709f79b46/cc28b985-fc11-449a-8aa3-e28a48a535d0/PXL_20230907_151219732.jpg', 90.00),

(3, 'Alpine Flora Identification Field Trip', 'Spend a day with me in the mountains learning how to identify endemic plant species. We will discuss the ecosystem, the challenges of high-altitude life, and how climate change is affecting these fragile habitats.', 'https://fastly.picsum.photos/id/519/200/200.jpg?hmac=7MwcBjyXrRX5GB6GuDATVm_6MFDRmZaSK7r5-jqDNS0', 60.00),
(3, 'Nature Photography Masterclass', 'Capture the wilderness like a pro. This course covers composition, lighting in diverse environments, and how to tell a story through botanical photography. Bring your camera and sturdy hiking boots.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 55.00),

(4, 'The Science of Espresso Extraction', 'Beyond the button press. Learn about grind size, water pressure, puck preparation, and the chemistry behind the perfect shot. We will dial in a coffee together until it tastes balanced and sweet.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 45.00),
(4, 'Jazz Bass Fundamentals', 'A beginner-friendly guide to walking bass lines and jazz improvisation. We will cover standard chord progressions, rhythm, and how to find your groove within an ensemble.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 35.00),

(5, 'Tech Startup Branding Strategy', 'How to define your voice in a crowded market. We will go over audience segmentation, content strategy, and how to build a brand identity that resonates with early adopters in the tech space.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 150.00),
(5, 'Professional Social Media Audit', 'Struggling to gain traction? I will provide a deep dive into your current digital presence, offering actionable insights on how to improve your engagement and conversion rates.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 85.00),

(6, 'Danish Modern Furniture Workshop', 'Learn to build a simple, elegant side table using traditional joinery techniques. We emphasize functionality, clean lines, and high-quality craftsmanship.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 200.00),
(6, 'Introduction to Nordic Woodworking', 'Learn the basics of hand-tool woodworking. We will cover timber selection, sharpening your chisels, and the basics of creating durable, beautiful joints that last a lifetime.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 110.00),

(7, 'Introduction to Civil Rights Advocacy', 'A foundational course on understanding your rights and how to navigate legal systems. We will look at case studies from around the world and discuss how to engage in ethical advocacy.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 65.00),
(7, 'Traditional Weaving Workshop', 'A workshop on Senegalese weaving techniques. This is a chance to learn a beautiful, ancient craft while we discuss the history and cultural significance of textile arts in West Africa.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 50.00),

(8, 'Authentic Sourdough Baking', 'Forget store-bought loaves. Learn how to create, feed, and maintain your own sourdough starter, and master the art of the perfect, crusty artisan loaf.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 40.00),
(8, 'Italian Home Cooking Secrets', 'Simple, high-quality ingredients made right. We will focus on the fundamentals of handmade pasta, perfect marinara, and classic desserts that impress every time.', 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg', 55.00);



