export const categories = [
    "All",
    "Math & Physics",
    "Foreign Languages",
    "Language & Literature",
    "Biology & Chemistry",
    "IT & Programming",
    "Music & Arts",
];

export const mockListings = [
    {
        id: 1,
        name: "Mariam Gelashvili",
        subject: "Mathematics",
        category: "Math & Physics",
        price: 30,
        location: "Tbilisi, Vake",
        rating: 4.8,
        reviewCount: 24,
        description:
            "10 years of experience. I prepare students for graduation and national exams. Individual approach for every student.",
        phone: "555 12 34 56",
        experience: 10,
        online: false,
    },
    {
        id: 2,
        name: "Giorgi Beridze",
        subject: "Physics",
        category: "Math & Physics",
        price: 25,
        location: "Tbilisi, Saburtalo",
        rating: 4.5,
        reviewCount: 17,
        description:
            "Physics faculty graduate of TSU. I prepare students for national exams and olympiads.",
        phone: "555 98 76 54",
        experience: 7,
        online: true,
    },
    {
        id: 3,
        name: "Nino Javakhishvili",
        subject: "English Language",
        category: "Foreign Languages",
        price: 20,
        location: "Tbilisi, Isani",
        rating: 4.9,
        reviewCount: 41,
        description:
            "IELTS and TOEFL preparation. C2 level certified. I also offer online lessons. All ages welcome.",
        phone: "555 11 22 33",
        experience: 12,
        online: true,
    },
    {
        id: 4,
        name: "Davit Maisuradze",
        subject: "Chemistry",
        category: "Biology & Chemistry",
        price: 35,
        location: "Tbilisi, Gldani",
        rating: 4.7,
        reviewCount: 12,
        description:
            "Olympiad winner. Preparation for medical school entrance and national exams. Practical lab sessions included.",
        phone: "555 44 55 66",
        experience: 5,
        online: false,
    },
    {
        id: 5,
        name: "Salome Kvaratskhelia",
        subject: "Georgian Language & Literature",
        category: "Language & Literature",
        price: 15,
        location: "Tbilisi, Didube",
        rating: 4.6,
        reviewCount: 30,
        description:
            "Literature, language, essay writing. High scores on national exams. Students of all ages.",
        phone: "555 77 88 99",
        experience: 8,
        online: true,
    },
    {
        id: 6,
        name: "Luka Tavdgiridze",
        subject: "Programming",
        category: "IT & Programming",
        price: 40,
        location: "Online",
        rating: 5.0,
        reviewCount: 8,
        description:
            "Python, Java, JavaScript. From beginner to advanced. Practical projects and real-world assignments.",
        phone: "555 00 11 22",
        experience: 4,
        online: true,
    },
    {
        id: 7,
        name: "Tamar Eliashvili",
        subject: "German Language",
        category: "Foreign Languages",
        price: 22,
        location: "Tbilisi, Vake",
        rating: 4.4,
        reviewCount: 19,
        description:
            "Goethe Institute certified. A1-B2 levels. Conversation practice and grammar fundamentals.",
        phone: "555 33 44 55",
        experience: 6,
        online: false,
    },
    {
        id: 8,
        name: "Zurab Kharabadze",
        subject: "Biology",
        category: "Biology & Chemistry",
        price: 28,
        location: "Kutaisi",
        rating: 4.3,
        reviewCount: 22,
        description:
            "Preparation for medical university entrance exams. 8 years of experience. Detailed study materials.",
        phone: "555 66 77 88",
        experience: 8,
        online: false,
    },
    {
        id: 9,
        name: "Ana Mchedlidze",
        subject: "French Language",
        category: "Foreign Languages",
        price: 25,
        location: "Tbilisi, Mtatsminda",
        rating: 4.7,
        reviewCount: 15,
        description:
            "Graduate of a university in Paris. DELF exam preparation. A1-C1 levels available.",
        phone: "555 99 00 11",
        experience: 9,
        online: true,
    },
    {
        id: 10,
        name: "Beka Chkheidze",
        subject: "Guitar",
        category: "Music & Arts",
        price: 20,
        location: "Tbilisi, Nadzaladevi",
        rating: 4.9,
        reviewCount: 35,
        description:
            "Classical and electric guitar. From beginners to professionals. Fun and effective lessons.",
        phone: "555 22 33 44",
        experience: 11,
        online: false,
    },
];